- id: merge-issue-number
  name: "Merge Issue Number"
  description: "Adds an Issue number from the branch to the commit message."
  language: python
  entry: merge-issue-number
  stages: [prepare-commit-msg]
